version: '3.8'

services:
  api-vida-edn:
    image: harbor.interseguro.com.pe/siv/api-vida-edn:dev
    container_name: api-vida-edn
    restart: unless-stopped
    env_file: .env
    ports:
      - "3063:8080"